In [1]:
# import numpy module
import numpy as np
import math

## the function returns the Gradient vector at the input vector x_i
## note: the expression of each element in the Gradient vector is hard-coded based on the formula presented above, which is also given on Slide 45 of Topic 3.2
def getGradientVector(x_i):
  g = np.zeros((3,1))
  g[0] = 4 * (x_i[0] - 4) * (x_i[0] - 4) * (x_i[0] - 4) + 2 * (x_i[0] - x_i[1]) + 4 * (x_i[0] + 2 * x_i[2])
  g[1] = -2 * (x_i[0] - x_i[1])
  g[2] =  8 * (x_i[0] + 2 * x_i[2])
  return g

# the function returns the norm of an input vector
def getNorm(v):
  return math.sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2])

## the function returns the Hessian matrix at the vector x_i
## note: the expression of each element in the Hessian matrix is hard-coded based on the formula presented above, which is also given on Slide 45 of Topic 3.2
def getHessianMatrix(x_i):
  H = np.zeros((3,3))
  
  H[0, 0] = 12 * (x_i[0] - 4) * (x_i[0] - 4) + 6
  H[0, 1] = -2
  H[0, 2] = 8

  H[1, 0] = -2
  H[1, 1] = 2
  H[1, 2] = 0

  H[2, 0] = 8
  H[2, 1] = 0
  H[2, 2] = 16

  return H


## set an initial guess
x_0 = np.array([[3], [-1], [0]])
print(f"--The initial guess x0: ")
print(x_0)

## set a threshold value for getting a good solution
thresh = 0.01

x_i = x_0
count = 0
while True:
  print('****************************************************')
  print(f'--At iteration: {count}')
  
  ## compute the gradient vector at x_i
  g = getGradientVector(x_i)
  print(f"--The gradient vector g(x_{count}): ")
  print(g)

  ## compute the norm of the gradient vector at x_i
  normOfGradient = getNorm(g)
  print(f"--The norm of the gradient vector |g(x_{count})|: {normOfGradient}")

  ## check if converged; if true, then stop; continue otherwise
  if normOfGradient <= thresh:
    break

  ## compute the Hessian matrix at x_i
  H = getHessianMatrix(x_i)
  print(f"--The Hessian matrix H(x_{count}): ")
  print(H)

  ## solve the linear system  Hh=-g
  h_i = np.linalg.solve(H, -1*g)
  print(f"--The h vector h_{count}: ")
  print(h_i)

  ## get the new solution point
  x_i_plus1 = x_i + h_i
  print(f"--The solution vector x_{count+1}: ")
  print(x_i_plus1)

  x_i = x_i_plus1
  count = count + 1
  print()

--The initial guess x0: 
[[ 3]
 [-1]
 [ 0]]
****************************************************
--At iteration: 0
--The gradient vector g(x_0): 
[[16.]
 [-8.]
 [24.]]
--The norm of the gradient vector |g(x_0)|: 29.93325909419153
--The Hessian matrix H(x_0): 
[[18. -2.  8.]
 [-2.  2.  0.]
 [ 8.  0. 16.]]
--The h vector h_0: 
[[ 0.33333333]
 [ 4.33333333]
 [-1.66666667]]
--The solution vector x_1: 
[[ 3.33333333]
 [ 3.33333333]
 [-1.66666667]]

****************************************************
--At iteration: 1
--The gradient vector g(x_1): 
[[-1.18518519e+00]
 [ 8.88178420e-16]
 [ 0.00000000e+00]]
--The norm of the gradient vector |g(x_1)|: 1.1851851851851853
--The Hessian matrix H(x_1): 
[[11.33333333 -2.          8.        ]
 [-2.          2.          0.        ]
 [ 8.          0.         16.        ]]
--The h vector h_1: 
[[ 0.22222222]
 [ 0.22222222]
 [-0.11111111]]
--The solution vector x_2: 
[[ 3.55555556]
 [ 3.55555556]
 [-1.77777778]]

***************************************